"""

Revision ID: 52140b3ada8a
Revises: 
Create Date: 2022-11-01 09:21:42.693879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52140b3ada8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchorpos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('construction',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('references', sa.UnicodeText(), nullable=True),
    sa.Column('family', sa.UnicodeText(), nullable=True),
    sa.Column('name_ud', sa.UnicodeText(), nullable=True),
    sa.Column('illustration', sa.UnicodeText(), nullable=False),
    sa.Column('cefr_level', sa.Enum('a1', 'a2', 'b1', 'b2', 'c1', 'c2', name='cefrlevel'), nullable=True),
    sa.Column('communicative_type', sa.Enum(name='communicativetype'), nullable=True),
    sa.Column('usage_label', sa.Enum('colloquial', 'formal', 'na', name='usagelabel'), nullable=True),
    sa.Column('anchor_words', sa.UnicodeText(), nullable=True),
    sa.Column('common_fillers', sa.UnicodeText(), nullable=True),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('dependency_structure', sa.UnicodeText(), nullable=True),
    sa.Column('illustration_dependency_structure', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_cefr_level'), 'construction', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_construction_communicative_type'), 'construction', ['communicative_type'], unique=False)
    op.create_index(op.f('ix_construction_illustration'), 'construction', ['illustration'], unique=False)
    op.create_index(op.f('ix_construction_name'), 'construction', ['name'], unique=False)
    op.create_index(op.f('ix_construction_name_ud'), 'construction', ['name_ud'], unique=False)
    op.create_index(op.f('ix_construction_usage_label'), 'construction', ['usage_label'], unique=False)
    op.create_table('morphologicaltag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('semanticrole',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('semantictype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('syntacticfunction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('syntactictype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('anchorpos2construction',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['anchorpos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('number', 'left_id', 'right_id')
    )
    op.create_table('constructiondefinition',
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', 'norwegian', name='language'), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('construction_id', 'language')
    )
    op.create_table('constructionexample',
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', 'norwegian', name='language'), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('construction_id', 'number', 'language')
    )
    op.create_table('morphologicaltag2construction',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['morphologicaltag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('number', 'left_id', 'right_id')
    )
    op.create_table('semanticrole2construction',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['semanticrole.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('semantictype2construction',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['semantictype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('syntacticfunction2construction',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['syntacticfunction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('syntactictype2construction',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['syntactictype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_id'], ['construction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_usage', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_table('token')
    op.drop_table('syntactictype2construction')
    op.drop_table('syntacticfunction2construction')
    op.drop_table('semantictype2construction')
    op.drop_table('semanticrole2construction')
    op.drop_table('morphologicaltag2construction')
    op.drop_table('constructionexample')
    op.drop_table('constructiondefinition')
    op.drop_table('anchorpos2construction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('syntactictype')
    op.drop_table('syntacticfunction')
    op.drop_table('semantictype')
    op.drop_table('semanticrole')
    op.drop_table('morphologicaltag')
    op.drop_index(op.f('ix_construction_usage_label'), table_name='construction')
    op.drop_index(op.f('ix_construction_name_ud'), table_name='construction')
    op.drop_index(op.f('ix_construction_name'), table_name='construction')
    op.drop_index(op.f('ix_construction_illustration'), table_name='construction')
    op.drop_index(op.f('ix_construction_communicative_type'), table_name='construction')
    op.drop_index(op.f('ix_construction_cefr_level'), table_name='construction')
    op.drop_table('construction')
    op.drop_table('anchorpos')
    # ### end Alembic commands ###
