"""

Revision ID: 6a8362c400dc
Revises: 92f05a99bfe1
Create Date: 2023-09-27 11:05:38.314434

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '6a8362c400dc'
down_revision = '92f05a99bfe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossindex',
    sa.Column('construction_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.id'], name=op.f('fk_glossindex_construction_id_construction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossindex'))
    )
    with op.batch_alter_table('glossindex', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossindex_attr'), ['attr'], unique=False)
        batch_op.create_index(batch_op.f('ix_glossindex_root'), ['root'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glossindex', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossindex_root'))
        batch_op.drop_index(batch_op.f('ix_glossindex_attr'))

    op.drop_table('glossindex')
    # ### end Alembic commands ###
