"""

Revision ID: 92f05a99bfe1
Revises: d85884e8e35a
Create Date: 2023-09-12 17:57:06.530541

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '92f05a99bfe1'
down_revision = 'd85884e8e35a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gloss',
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', 'norwegian', name='language'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['construction.id'], name=op.f('fk_gloss_construction_id_construction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('construction_id', 'language', 'number', name=op.f('pk_gloss'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gloss')
    # ### end Alembic commands ###
