"""

Revision ID: bf85ffea75af
Revises: 52140b3ada8a
Create Date: 2022-11-01 10:21:55.001923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf85ffea75af'
down_revision = '52140b3ada8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singleton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('singleton')
    # ### end Alembic commands ###
